[package]
name = "blendhit_escrow"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
borsh = "0.9"
solana-program = "1.14.4"
thiserror = "1.0"
spl-token = {version = "3.2.0", features = ["no-entrypoint"]}

[lib]
crate-type = ["cdylib", "lib"]